/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TokoBunga;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TokoBunga.DbUtils;

/**
 *
 * @author Huawei
 */
public class TokoBunga extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/DB_PBO_P4";
    String user = "postgres";
    String password = "1234";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);

    public TokoBunga() {
        initComponents();
        showTable();
    }

    private void bersih() {
        TxtIdBunga.setText("");
        TxtNamaBunga.setText("");
        TxtKategoriBunga.setText("");
        TxtDeskripsiProduk.setText("");
        TxtHarga.setText("");
        TxtStokBunga.setText("");
        TxtUkuranBuket.setText("");
    }

    public void showTable() {
        String[] kolom = {"ID Bunga", "Nama Bunga", "Kategori Bunga",
            "Deskripsi Produk", "Harga", "Stok Bunga", "Ukuran Buket"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        jTable1.setModel(model);

        try {
            Class.forName(driver);
            String sql = "SELECT * FROM tokobunga ORDER BY idbunga";
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String id = rs.getString("idbunga");
                String nama = rs.getString("namabunga");
                String kategori = rs.getString("kategoribunga");
                String deskripsi = rs.getString("deskripsiproduk");
                int harga = rs.getInt("harga");
                int stok = rs.getInt("stok");
                String ukuran = rs.getString("ukuran");

                Object[] data = {id, nama, kategori, deskripsi, harga, stok, ukuran};
                model.addRow(data);
            }

            rs.close();
            stmt.close();
            conn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtIdBunga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtNamaBunga = new javax.swing.JTextField();
        TxtKategoriBunga = new javax.swing.JTextField();
        TxtDeskripsiProduk = new javax.swing.JTextField();
        TxtHarga = new javax.swing.JTextField();
        TxtStokBunga = new javax.swing.JTextField();
        TxtUkuranBuket = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnInsert = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtIdBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdBungaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtIdBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 390, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Data Buket Bunga ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 490, -1));

        TxtNamaBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaBungaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtNamaBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 390, -1));

        TxtKategoriBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKategoriBungaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtKategoriBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 390, -1));

        TxtDeskripsiProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDeskripsiProdukActionPerformed(evt);
            }
        });
        getContentPane().add(TxtDeskripsiProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 390, 60));

        TxtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHargaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 390, -1));

        TxtStokBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStokBungaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtStokBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 390, -1));

        TxtUkuranBuket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUkuranBuketActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUkuranBuket, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 390, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("ID Bunga");
        jLabel2.setAutoscrolls(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 87, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("Nama Bunga");
        jLabel3.setAutoscrolls(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Kategori Bunga");
        jLabel4.setAutoscrolls(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Deskripsi Produk");
        jLabel5.setAutoscrolls(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Harga");
        jLabel6.setAutoscrolls(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 63, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("Ukuran Buket");
        jLabel8.setAutoscrolls(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText(" Stok Bunga");
        jLabel7.setAutoscrolls(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 90, -1));

        BtnInsert.setBackground(new java.awt.Color(255, 102, 204));
        BtnInsert.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnInsert.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsert.setText("Insert");
        BtnInsert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(BtnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 100, 30));
        BtnInsert.getAccessibleContext().setAccessibleDescription("");

        BtnUpdate.setBackground(new java.awt.Color(255, 102, 204));
        BtnUpdate.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 100, 30));
        BtnUpdate.getAccessibleContext().setAccessibleDescription("");

        BtnDelete.setBackground(new java.awt.Color(255, 102, 204));
        BtnDelete.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Delete");
        BtnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 100, 30));
        BtnDelete.getAccessibleContext().setAccessibleDescription("");

        BtnClear.setBackground(new java.awt.Color(255, 102, 204));
        BtnClear.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnClear.setForeground(new java.awt.Color(255, 255, 255));
        BtnClear.setText("Clear");
        BtnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 100, 30));
        BtnClear.getAccessibleContext().setAccessibleDescription("");

        BtnExit.setBackground(new java.awt.Color(204, 0, 0));
        BtnExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnExit.setText("X");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        jTable1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Bunga", "Nama Bunga", "Kategori Bunga", "Deskripsi Produk", "Harga", "Stok Bunga", "Ukuran Buket"
            }
        ));
        jTable1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTable1MouseWheelMoved(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 690, 160));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TokoBunga/bunga 2.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNamaBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaBungaActionPerformed

    private void TxtKategoriBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKategoriBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKategoriBungaActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        String idbunga, namabunga, kategoribunga, deskripsiproduk, ukuran;
        int harga, stok;
        if (TxtIdBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtNamaBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtKategoriBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtDeskripsiProduk.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtStokBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtUkuranBuket.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
                conn.setAutoCommit(false);

                String sql = "UPDATE tokobunga SET namabunga= ?, kategoribunga= ?, deskripsiproduk= ?, harga= ?, stok= ?, ukuran= ? WHERE idbunga= ?";
                conn = DriverManager.getConnection(koneksi, user, password);
                pstmt = conn.prepareStatement(sql);

                idbunga = TxtIdBunga.getText();
                namabunga = TxtNamaBunga.getText();
                kategoribunga = TxtKategoriBunga.getText();
                deskripsiproduk = TxtDeskripsiProduk.getText();
                harga = Integer.parseInt(TxtHarga.getText());
                stok = Integer.parseInt(TxtStokBunga.getText());
                ukuran = TxtUkuranBuket.getText();

                pstmt.setString(1, namabunga);
                pstmt.setString(2, kategoribunga);
                pstmt.setString(3, deskripsiproduk);
                pstmt.setInt(4, harga);
                pstmt.setInt(5, stok);
                pstmt.setString(6, ukuran);
                pstmt.setString(7, idbunga);

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil diupdate");
                    pstmt.close();
                    conn.close();
                    bersih();
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        showTable();
    }//GEN-LAST:event_BtnUpdateActionPerformed


    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        if (TxtIdBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtNamaBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtKategoriBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtDeskripsiProduk.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtStokBunga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else if (TxtUkuranBuket.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi semua data");
        } else {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
                conn.setAutoCommit(false);

                String sql = "INSERT INTO tokobunga VALUES(?,?,?,?,?,?,?)";
                pstmt = conn.prepareStatement(sql);

                String idbunga, namabunga, kategoribunga, deskripsiproduk, ukuran;
                int harga, stok;
                idbunga = TxtIdBunga.getText();
                namabunga = TxtNamaBunga.getText();
                kategoribunga = TxtKategoriBunga.getText();
                deskripsiproduk = TxtDeskripsiProduk.getText();
                harga = Integer.parseInt(TxtHarga.getText());
                stok = Integer.parseInt(TxtStokBunga.getText());
                ukuran = TxtUkuranBuket.getText();

                pstmt.setString(1, idbunga);
                pstmt.setString(2, namabunga);
                pstmt.setString(3, kategoribunga);
                pstmt.setString(4, deskripsiproduk);
                pstmt.setInt(5, harga);
                pstmt.setInt(6, stok);
                pstmt.setString(7, ukuran);

                pstmt.executeUpdate();
                conn.commit();
                pstmt.close();
                conn.close();

                JOptionPane.showMessageDialog(null, "Sukses diinput");
            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat pengisian");
            }
        }
        bersih();
        showTable();
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        bersih();
    }//GEN-LAST:event_BtnClearActionPerformed

    private void TxtIdBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdBungaActionPerformed

    private void TxtDeskripsiProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDeskripsiProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDeskripsiProdukActionPerformed

    private void TxtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHargaActionPerformed

    private void TxtStokBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStokBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStokBungaActionPerformed

    private void TxtUkuranBuketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUkuranBuketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUkuranBuketActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        String idbunga;
        idbunga = TxtIdBunga.getText();

        try {
            Class.forName(driver);
            conn = DriverManager.getConnection(koneksi, user, password);

            int jawab = JOptionPane.showConfirmDialog(null, "Silakan Konfirmasi?");
            switch (jawab) {
                case JOptionPane.YES_OPTION:
                    String deleteSql = "DELETE FROM tokobunga WHERE idbunga= ?";
                    pstmt = conn.prepareStatement(deleteSql);
                    pstmt.setString(1, idbunga);
                    pstmt.executeUpdate();
                    pstmt.close();
                    conn.close();
                    bersih();
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(this, "Kamu menjawab tidak");
                    break;
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showConfirmDialog(null, "Cek Lagi!!!");
            Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
        }
        showTable();
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.getSelectedRow();
        TxtIdBunga.setText(jTable1.getValueAt(row, 0).toString());
        TxtNamaBunga.setText(jTable1.getValueAt(row, 1).toString());
        TxtKategoriBunga.setText(jTable1.getValueAt(row, 2).toString());
        TxtDeskripsiProduk.setText(jTable1.getValueAt(row, 3).toString());
        TxtHarga.setText(jTable1.getValueAt(row, 4).toString());
        TxtStokBunga.setText(jTable1.getValueAt(row, 5).toString());
        TxtUkuranBuket.setText(jTable1.getValueAt(row, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTable1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoBunga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JTextField TxtDeskripsiProduk;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtIdBunga;
    private javax.swing.JTextField TxtKategoriBunga;
    private javax.swing.JTextField TxtNamaBunga;
    private javax.swing.JTextField TxtStokBunga;
    private javax.swing.JTextField TxtUkuranBuket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
